sql:
  Database: test
  User: test
  Password: test
skills:
  mining:
    Title: Mining
    SkillPointFactor: 100
    sp:
      Emerald_Ore: 150
      Diamond_Ore: 100
      Quartz_Ore: 10
      Gold_Ore: 20
      Lapis_Ore: 20
      Iron_Ore: 10
      Redstone_Ore: 5
      Glowing_Redstone_Ore: 5
      Coal_Ore: 2
    xp:
      Iron_Ore: 3 
      Gold_Ore: 5
  smelting:
    Title: Smelting
    SkillPointFactor: 100
    sp:
      Emerald: 20
      Diamond: 20
      Quartz: 20
      Gold_Ingot: 20
      Iron_Ingot: 10
      Coal: 10
      Ink_Sack: 20
      Cooked_Beef: 2
      Cooked_Chicken: 2
      Cooked_Fish: 2
      Grilled_Pork: 2
      Stone: 1
    xp: {}
  eating:
    Title: Eating
    SkillPointFactor: 10
    LevelsPerHealthPoint: 100
    food:
      BREAD: 5
      CARROT_ITEM: 4
      BAKED_POTATO: 6
      POTATO_ITEM: 1
      POISONOUS_POTATO: 2
      GOLDEN_CARROT: 6
      PUMPKIN_PIE: 8
      COOKIE: 2
      MELON: 2
      MUSHROOM_SOUP: 6
      RAW_CHICKEN: 2
      COOKED_CHICKEN: 6
      RAW_BEEF: 3
      COOKED_BEEF: 8
      RAW_FISH: 2
      COOKED_FISH: 5
      PORK: 3
      GRILLED_PORK: 8
      APPLE: 4
      GOLDEN_APPLE: 4
      ROTTEN_FLESH: 4
      SPIDER_EYE: 2
      CAKE: 2
    sp:
      BREAD: 5
      CARROT_ITEM: 4
      BAKED_POTATO: 6
      POTATO_ITEM: 1
      POISONOUS_POTATO: 2
      GOLDEN_CARROT: 6
      PUMPKIN_PIE: 8
      COOKIE: 2
      MELON: 2
      MUSHROOM_SOUP: 6
      RAW_CHICKEN: 2
      COOKED_CHICKEN: 6
      RAW_BEEF: 3
      COOKED_BEEF: 8
      RAW_FISH: 2
      COOKED_FISH: 5
      PORK: 3
      GRILLED_PORK: 8
      APPLE: 4
      GOLDEN_APPLE: 4
      ROTTEN_FLESH: 0
      SPIDER_EYE: 2
      CAKE: 2
  herbalism:
    Title: Herbalism
    SkillPointFactor: 10
    structures:
    sp:
      structures:
        Tree: 5
        Swamp: 5
        Big_Tree: 5
        Birch: 10
        Jungle_Bush: 10
        Redwood: 10
        Tall_Redwood: 10
        Small_Jungle: 20
        Red_Mushroom: 50
        Brown_Mushroom: 50
        Jungle: 80
      blocks:
        Crops: 1
        Carrot: 1
        Potato: 1
        Log: 1
        Leaves: 1
        Pumpkin: 1
        Melon_Block: 1
        Vine: 1
        Sugar_Cane_Block: 1
        Water_Lily: 10
  travelling:
    Title: Travelling
    SkillPointFactor: 10
    NormDistance: 16
    MinPearlingDistance: 16
    WalkingSkillPoints: 10
    SprintingSkillPoints: 20
    PearlingSkillPoints: 30
  wildlife:
    Title: Wildlife
    SkillPointFactor: 10
    sp:
      Shearing: 5
      Fishing: 10
      breeding:
        Chicken: 1
        Cow: 5
        Mushroom_Cow: 5
        Ocelot: 10
        Pig: 5
        Sheep: 5
        Wolf: 5
      taming:
        Ocelot: 100
        Wolf: 100
    xp:
      breeding:
        Chicken: 5
        Cow: 5
        Mushroom_Cow: 5
        Ocelot: 5
        Pig: 5
        Sheep: 5
        Wolf: 5
  melee:
    Title: Melee
    SkillPointFactor: 10
    MinKillDistance: 5
    sp:
      Silverfish: 5
      Slime: 5
      Cave_Spider: 10
      Enderman: 10
      Pig_Zombie: 10
      Skeleton: 10
      Spider: 10
      Witch: 10
      Zombie: 10
      Magma_Cube: 10
      Blaze: 20
      Creeper: 30
      Giant: 50
      Wither: 100
      Ender_Dragon: 100
  archery:
    Title: Archery
    SkillPointFactor: 5
    MinKillDistance: 15
    NormDistance: 16
    sp:
      Silverfish: 5
      Slime: 5
      Cave_Spider: 10
      Enderman: 10
      Pig_Zombie: 10
      Skeleton: 10
      Spider: 10
      Witch: 10
      Zombie: 10
      Magma_Cube: 10
      Blaze: 20
      Creeper: 30
      Giant: 50
      Wither: 100
      Ender_Dragon: 100
