sql:
  Database: test
  User: test
  Password: test
skills:
  mining:
    Description: |-
      Break stone and valuable ores with your pickaxe.
      Skill points are given for stone, sandstone, coal, iron, gold, redstone, lapis, diamonds, emeralds and quartz.
      Broken ores will drop more experience points as you climb up levels.
    sp:
      Emerald-Ore: 50
      Diamond-Ore: 30 # 50 | 10
      Gold-Ore: 20 # 20 | 10
      Lapis-Ore: 30 # 45 | 15
      Redstone-Ore: 5 # 6 | 1.5
      Glowing-Redstone-Ore: 5 # 6 | 1.5
      Quartz-Ore: 2
      Iron-Ore: 2 # 2 | 1.75
      Coal-Ore: 1
      Obsidian: 1
      Sandstone: 1/2
      Stone: 1/16
    xp:
      Iron-Ore: 3 
      Gold-Ore: 5
  alchemy:
    Description: |-
      Refine materials in a furnace. You earn skill points as you take the end result out.
      Earn skill points for cooking food, stone, dyes and ores.
      The amount of dropped experience points increases as you level up.
    sp:
      smelting:
        Emerald: 4
        Diamond: 2
        Gold-Ingot: 2
        Quartz: 1
        Iron-Ingot: 1
        Quartz: 1
        Coal: 1
        Ink-Sack: 1/2
        Cooked-Beef: 1/2
        Cooked-Fish: 1/2
        Grilled-Pork: 1/2
        Cooked-Chicken: 1/4
        Stone: 1/16
      blasting:
        Emerald-Ore: 50
        Diamond-Ore: 30
        Gold-Ore: 20
        Lapis-Ore: 30
        Redstone-Ore: 5
        Glowing-Redstone-Ore: 5
        Quartz-Ore: 2
        Iron-Ore: 2
        Coal-Ore: 1
        Obsidian: 1
        Sandstone: 1/2
        Stone: 1/16
    xp: {}
  eating:
    Description: |-
      Fill up your hunger bar by eating good foods.
      Get the more skill points the healthier and more delicious your diet is.
      Eating food gives you a health boost depending on your skill level.
    LevelsPerHealthPoint: 100
    food:
      Bread: 5
      Carrot-Item: 4
      Baked-Potato: 6
      Potato-Item: 1
      Poisonous-Potato: 2
      Golden-Carrot: 6
      Pumpkin-Pie: 8
      Cookie: 2
      Melon: 2
      Mushroom-Soup: 6
      Raw-Chicken: 2
      Cooked-Chicken: 6
      Raw-Beef: 3
      Cooked-Beef: 8
      Raw-Fish: 2
      Cooked-Fish: 5
      Pork: 3
      Grilled-Pork: 8
      Apple: 4
      Golden-Apple: 4
      Rotten-Flesh: 4
      Spider-Eye: 2
      Cake: 2
    sp:
      Bread: 5
      Carrot-Item: 4
      Baked-Potato: 6
      Potato-Item: 1
      Poisonous-Potato: 2
      Golden-Carrot: 6
      Pumpkin-Pie: 8
      Cookie: 2
      Melon: 2
      Mushroom-Soup: 6
      Raw-Chicken: 2
      Cooked-Chicken: 6
      Raw-Beef: 3
      Cooked-Beef: 8
      Raw-Fish: 2
      Cooked-Fish: 5
      Pork: 3
      Grilled-Pork: 8
      Apple: 4
      Golden-Apple: 4
      Rotten-Flesh: 0
      Spider-Eye: 0
      Cake: 2
  herbalism:
    Description: |-
      Cultivate and harvest growing things.
      Earn skill points for fertilizing and harvesting trees, wheat, vegetables, fruit and other plants.
    sp:
      fertilize:
        Crops: 1
        Carrot: 1
        Potato: 1
        Melon_Stem: 3
        Pumpkin_Stem: 3
        # The following should be covered by structures.
        #Sapling: 5
        #Red-Mushroom: 7
        #Brown-Mushroom: 7        
      harvest:
        Long-Grass: 1/16
        Dead-Bush: 1/8
        Log: 1/4
        Leaves: 1/4
        Crops: 1
        Carrot: 1
        Potato: 1
        Cactus: 1
        Pumpkin: 1
        Melon-Block: 1
        Vine: 1
        Sugar-Cane-Block: 1
        Red-Rose: 2
        Yellow-Flower: 2
        Water-Lily: 10
      structures:
        Tree: 3
        Swamp: 3
        Big-Tree: 3
        Birch: 6
        Jungle-Bush: 6
        Redwood: 6
        Tall-Redwood: 6
        Small-Jungle: 12
        Red-Mushroom: 24
        Brown-Mushroom: 24
        Jungle: 48
  traveling:
    Description: |-
      Explore the world of Winthier.
      Traveling long distances by foot, pig, horse or ender pearl gives you skill points.
    NormDistance: 16
    MinPearlingDistance: 32
    WalkingSkillPoints: 1
    SprintingSkillPoints: 3
    PearlingSkillPoints: 5
    RidingSkillPoints: 10
    FarTravelDistance: 64
  wildlife:
    Description: |-
      Take care of wild and farm animals.
      Collect skill points by taming, breeding, shearing different animals or catching fish.
      As you level up this skill, you will have more luck catching fish and get more experience points for fishing and breeding.
    sp:
      Shearing: 1
      Fishing: 8
      breeding:
        Chicken: 1
        Cow: 4
        Mushroom-Cow: 4
        Pig: 4
        Sheep: 4
        Ocelot: 8
        Wolf: 8
      taming:
        Ocelot: 20
        Wolf: 20
    xp:
      breeding:
        Chicken: 5
        Cow: 5
        Mushroom-Cow: 5
        Ocelot: 5
        Pig: 5
        Sheep: 5
        Wolf: 5
  melee:
    Description: |-
      Fight hostile mobs in close combat.
      You gain skill points by killing monsters with swords, axes or your fists. You get different amounts for zombies, skeletons, creepers and more.
      The higher your level is, the more experience points your victims will drop.
    MinKillDistance: 5
    sp:
      Silverfish: 1
      Slime: 1
      Cave-Spider: 2
      Enderman: 2
      Pig-Zombie: 2
      Skeleton: 2
      Spider: 2
      Zombie: 2
      Magma-Cube: 2
      Blaze: 4
      Witch: 5
      Creeper: 5
      Giant: 10
      Wither: 20
      Ender-Dragon: 50
  archery:
    Description: |-
      Snipe hostile mobs from a distance with ranged weapons.
      Use your bow to kill monsters from a distance. The farther away you are from your target, the more skill points you gain.
      Your prey will drop bonus experience points the higher your skill level is.
    MinKillDistance: 15
    NormDistance: 16
    sp:
      Silverfish: 1
      Slime: 1
      Cave-Spider: 2
      Enderman: 2
      Pig-Zombie: 2
      Skeleton: 2
      Spider: 2
      Zombie: 2
      Magma-Cube: 2
      Blaze: 4
      Witch: 5
      Creeper: 5
      Giant: 10
      Wither: 20
      Ender-Dragon: 50
  enchanting:
    Description: |-
      Enchant tools, weapons, armor or books on the enchanting table.
      Different materials give different amounts of skill points, multiplied with the experience level used.
    sp:
      Book: 1

      Wood-Pickaxe: 1/30
      Wood-Spade: 1/30
      Wood-Axe: 1/30
      Wood-Sword: 1/30

      Stone-Pickaxe: 1/10
      Stone-Spade: 1/10
      Stone-Axe: 1/10
      Stone-Sword: 1/10

      Iron-Pickaxe: 1/3
      Iron-Spade: 1/3
      Iron-Axe: 1/3
      Iron-Sword: 1/3

      Gold-Pickaxe: 1/2
      Gold-Spade: 1/2
      Gold-Axe: 1/2
      Gold-Sword: 1/2

      Diamond-Pickaxe: 2
      Diamond-Spade: 2
      Diamond-Axe: 2
      Diamond-Sword: 2

      Leather-Helmet: 1/10
      Leather-Chestplate: 1/10
      Leather-Leggings: 1/10
      Leather-Boots: 1/10

      Iron-Helmet: 1/3
      Iron-Chestplate: 1/3
      Iron-Leggings: 1/3
      Iron-Boots: 1/3

      Gold-Helmet: 1/2
      Gold-Chestplate: 1/2
      Gold-Leggings: 1/2
      Gold-Boots: 1/2

      Diamond-Helmet: 3
      Diamond-Chestplate: 3
      Diamond-Leggings: 3
      Diamond-Boots: 3
spells:
  health:
    DisplayName: Instant Health
    Description: health
    MinElementLevel: 10
    XPCost: 5
    Price: 1000
  increase-damage:
    DisplayName: Strength
    Description: increase-damage
    MinElementLevel: 10
    XPCost: 5
    Price: 1000
  fast-digging:
    DisplayName: Haste
    Description: fast-digging
    MinElementLevel: 10
    XPCost: 5
    Price: 1000
  speed:
    DisplayName: Swiftness
    Description: speed
    MinElementLevel: 10
    XPCost: 5
    Price: 1000
  regeneration:
    DisplayName: Regeneration
    Description: regeneration
    MinElementLevel: 10
    XPCost: 5
    Price: 1000
  fire-resistance:
    DisplayName: Fire Resistance
    Description: fire-resistance
    MinElementLevel: 10
    XPCost: 5
    Price: 1000
  damage-resistance:
    DisplayName: Resistance
    Description: damage-resistance
    MinElementLevel: 10
    XPCost: 5
    Price: 1000
  jump:
    DisplayName: Jump Boost
    Description: jump
    MinElementLevel: 10
    XPCost: 5
    Price: 1000
