name: Skills
description: A skill system for Winthier
author: StarTux
version: 0.1
main: com.winthier.skills.SkillsPlugin
depend: [ Exploits, ProtocolLib ]
commands:
  Skill:
    aliases: [ Skills, sk ]
    description: User interface for Skills.
    usage: /<command> [skilltype]
    permission: skills.skill
  Highscore:
    aliases: [ High, HiScore, hi ]
    usage: /<command> [skilltype]
    permission: skills.hi
  SkillConfig:
    aliases: [ SkillsConfig, skc ]
    description: Admin interface for Skills.
    usage: /<command> [skilltype]
    permission: skills.skillconfig
permissions:
  skills.skill:
    description: Use the /skill command.
    default: op
  skills.hi:
    description:
    description: Use the /hi command
    default: op
  skills.skillconfig:
    description: Use the /skillconfig command.
    default: op
  skills.play:
    description: Collect skill points.
    default: true