name: Skills
description: A skill system for Winthier
author: StarTux
version: 0.1
main: com.winthier.skills.SkillsPlugin
depend: [ Exploits ]
commands:
  skill:
    aliases: [ sk, skills, sks ]
    description: User interface for Skills
    permission: skills.skill
  skillconfig:
    aliases: [ skc, skillsconfig ]
    description: Admin interface for Skills
    permission: skills.skillconfig
permissions:
  skills.skill:
    description: Use the /skill command
    default: op
  skills.skill.other:
    description: Lookup skill info of other players
    default: op
  skills.skillconfig:
    description: Use the /skillconfig command
    default: op